Sing in and Sing up
chacaa/DoApp pull request #2
Opened 2017-03-10 21:19 UTC by chacaa

Adds the views and logic for the Signup and SignIn screens.

# Trello card:
* [Create Login View](https://trello.com/c/MSUde1Gu)
* [Create New Account Screen](https://trello.com/c/47ct435z)
* [Login logic](https://trello.com/c/s0T0Q1ME)
* [Create the logic for the create account screen](https://trello.com/c/GqxAFvx2)

# UI:
![UI](http://g.recordit.co/ZxtphCownA.gif)

2017-03-10 21:45 UTC, mirland requested changes
I couldn't finish the review, but you should review all the code basing in my comments. 
Also assign the reviewers to the pr

2017-03-10 21:45 UTC, matir91 commented on app/src/main/java/com/xmartlabs/doapp/ApplicationComponent.java
> +  void inject(SinginFragment loginFragment);
we use one group to fragments and one group to activities

2017-03-10 21:45 UTC, matir91 commented on app/src/main/java/com/xmartlabs/doapp/controller/UserController.java
> +
remove space

2017-03-10 21:45 UTC, matir91 commented on app/src/main/java/com/xmartlabs/doapp/MilisecondsLocalDateAdapter.java
> +public class MilisecondsLocalDateAdapter extends TypeConverter<Long, LocalDate> {
rename it to `LocalDateAdapter ` or `LocalDateDatabaseAdapter `. The milliseconds is not important here

2017-03-10 21:45 UTC, matir91 commented on app/src/main/java/com/xmartlabs/doapp/ui/BaseAppCompatActivity.java
> +}
add end line

2017-03-10 21:45 UTC, matir91 commented on app/src/main/java/com/xmartlabs/doapp/ui/FragmentWithDrawer.java
> +}
end line

2017-03-10 21:45 UTC, matir91 commented on app/src/main/java/com/xmartlabs/doapp/ui/SinginActivity.java
> +    return new SinginFragment();
what do you think of using `FragmentArgs` here?

2017-03-10 21:45 UTC, matir91 commented on app/src/main/java/com/xmartlabs/doapp/ui/SinginFragment.java
> +    if (aFieldIsNotCompleted()) {
the name of the functions should be positives

2017-03-10 21:45 UTC, matir91 commented on app/src/main/java/com/xmartlabs/doapp/ui/SinginFragment.java
> +      Snackbar.make(getView(), "User doesn't exists", Snackbar.LENGTH_SHORT).show();
use strings resources!

2017-03-10 21:45 UTC, matir91 commented on app/src/main/java/com/xmartlabs/doapp/ui/SinginFragment.java
> +      //TODO
todo?

2017-03-10 21:45 UTC, matir91 commented on app/src/main/java/com/xmartlabs/doapp/ui/SinginFragment.java
> +      Snackbar.make(getView(), "It's all good my friend!", Snackbar.LENGTH_SHORT).show();
too

2017-03-10 21:45 UTC, matir91 commented on app/src/main/java/com/xmartlabs/doapp/ui/SinginFragment.java
> +      Snackbar.make(getView(), "Wrong password", Snackbar.LENGTH_SHORT).show();
too and implemente `showToast` function in the base fragment.

2017-03-10 21:45 UTC, matir91 commented on app/src/main/java/com/xmartlabs/doapp/ui/SinginFragment.java
> +    String email = userEmailValue.toString().trim();
use inline variable

2017-03-10 21:45 UTC, matir91 commented on app/src/main/java/com/xmartlabs/doapp/ui/SinginFragment.java
> +      Snackbar.make(getView(), "Complete Username field", Snackbar.LENGTH_SHORT).show();
too

2017-03-10 21:45 UTC, matir91 commented on app/src/main/java/com/xmartlabs/doapp/ui/SinginFragment.java
> +      username.setHintTextColor(getResources().getColor(R.color.reddish_pink));
the function name should tell you that an error could be displayed

2017-03-10 21:45 UTC, matir91 commented on app/src/main/java/com/xmartlabs/doapp/ui/SinginFragment.java
> +    if (notHasText(password)) {
should be positive

2017-03-10 21:45 UTC, matir91 commented on app/src/main/java/com/xmartlabs/doapp/ui/SinginFragment.java
> +      Snackbar.make(getView(), "Complete Password field", Snackbar.LENGTH_SHORT).show();
too

2017-03-10 21:45 UTC, matir91 commented on app/src/main/java/com/xmartlabs/doapp/ui/SinginFragment.java
> +
space

2017-03-10 21:45 UTC, matir91 commented on app/src/main/java/com/xmartlabs/doapp/ui/SinginFragment.java
> +    UserController.getInstance().getUser(userEmail).subscribe(new SingleSubscriber<User>() {
you shouldn't use static, use injection! also put the subscribe in a new line

2017-03-10 21:45 UTC, matir91 commented on app/src/main/java/com/xmartlabs/doapp/ui/SinginFragment.java
> +        Snackbar.make(getView(), "Wrong email account", Snackbar.LENGTH_SHORT).show();
check that the view is alive and also use sr!

2017-03-10 21:45 UTC, matir91 commented on app/src/main/java/com/xmartlabs/doapp/ui/SingleFragmentWithToolbarActivity.java
> +}
endline

2017-03-10 21:45 UTC, matir91 commented on app/src/main/java/com/xmartlabs/doapp/ui/SingupActivity.java
> +        return new SingupFragment();
use fragment args

2017-03-10 21:45 UTC, matir91 commented on app/src/main/java/com/xmartlabs/doapp/ui/SingupFragment.java
> +  void onClickedSingIn() {
what do you think of `onSinginTapped`?

2017-03-10 21:45 UTC, matir91 commented on app/src/main/java/com/xmartlabs/doapp/ui/SingupFragment.java
> +  void onClickedSignUp() {
same here

2017-03-10 21:45 UTC, matir91 commented on app/src/main/java/com/xmartlabs/doapp/ui/SingupFragment.java
> +        user.getBirthday().getMonthValue() - 1,
isn't a better way?

2017-03-10 21:57 UTC, bryant1410 requested changes

2017-03-10 21:57 UTC, bryant1410 commented on app/src/main/AndroidManifest.xml
> +            android:value="fb54b0fcded49d3e82043de10c558d9ea0018076"
This key is no longer necessary here and can be put in a `fabric.properties` file. This helps to separate assets from code.

2017-03-10 21:57 UTC, bryant1410 commented on app/src/main/java/com/xmartlabs/doapp/ui/SinginFragment.java
> +    if (user == null){
space before brace

2017-03-10 21:57 UTC, bryant1410 commented on app/src/main/java/com/xmartlabs/doapp/ui/SingupFragment.java
> +    String month = date.getMonth().getValue() <= 9 ? "0" + date.getMonth().getValue() : date.getMonth().getValue() + "";
There are ways of converting dates to string in Java and in Android. Google it!

2017-03-10 21:57 UTC, bryant1410 commented on app/src/main/java/com/xmartlabs/doapp/ui/ValidatableFragment.java
> +}
here too

2017-03-10 21:57 UTC, bryant1410 commented on app/src/main/java/com/xmartlabs/doapp/ui/WelcomeActivity.java
> +}
the same

2017-03-10 21:57 UTC, bryant1410 commented on app/src/main/java/com/xmartlabs/doapp/ui/WelcomeFragment.java
> +public class WelcomeFragment extends BaseFragment {
So no MVP here?

2017-03-10 21:57 UTC, bryant1410 commented on app/src/main/res/layout/singup_fragment.xml
> +            android:nextFocusForward="@+id/editTextEmail"
alpha

2017-03-10 21:57 UTC, bryant1410 commented on app/src/main/res/layout/singup_fragment.xml
> +</RelativeLayout>
new line

2017-03-13 12:32 UTC, diegomedina248 requested changes

2017-03-13 12:32 UTC, diegomedina248 commented on app/src/main/java/com/xmartlabs/doapp/controller/UserController.java
> +  public static UserController getInstance() {
Use dagger to inject this dependency elsewhere instead of using a static variable

2017-03-13 12:32 UTC, diegomedina248 commented on app/src/main/java/com/xmartlabs/doapp/MilisecondsLocalDateAdapter.java
> +public class MilisecondsLocalDateAdapter extends TypeConverter<Long, LocalDate> {
This could be added to the Base Project

2017-03-13 12:32 UTC, diegomedina248 commented on app/src/main/java/com/xmartlabs/doapp/ui/SinginFragment.java
> +        Snackbar.make(getView(), "Wrong email account", Snackbar.LENGTH_SHORT).show();
Also, won't this error appear on each key tapped?

2017-03-13 12:32 UTC, diegomedina248 commented on app/src/main/java/com/xmartlabs/doapp/ui/SingupFragment.java
> +  @Override
add `@LayoutRes`

2017-03-13 12:32 UTC, diegomedina248 commented on app/src/main/java/com/xmartlabs/doapp/ui/SingupFragment.java
> +  void onClickedSingIn() {
or `onSignInClicked` to be consistent with SDK names

2017-03-13 12:32 UTC, diegomedina248 commented on app/src/main/java/com/xmartlabs/doapp/ui/SingupFragment.java
> +  private boolean notHasText(EditText editText) {
how about `hasText`?

2017-03-13 12:32 UTC, diegomedina248 commented on app/src/main/java/com/xmartlabs/doapp/ui/SingupFragment.java
> +    String month = date.getMonth().getValue() <= 9 ? "0" + date.getMonth().getValue() : date.getMonth().getValue() + "";
Specially with LocalDate :)

2017-03-13 12:32 UTC, diegomedina248 commented on app/src/main/java/com/xmartlabs/doapp/ui/SingupFragment.java
> +    UserController.getInstance().insertUser(user).subscribe(new SingleSubscriber<User>() {
injection

2017-03-13 12:32 UTC, diegomedina248 commented on app/src/main/java/com/xmartlabs/doapp/ui/SingupFragment.java
> +    return User.builder()
In this view, i guess having a dummy user is pointless.
You should retrieve the User object when the user taps the sign up button

2017-03-13 12:32 UTC, diegomedina248 commented on app/src/main/java/com/xmartlabs/doapp/ui/StartActivity.java
> +}
end line

2017-03-13 12:32 UTC, diegomedina248 commented on app/src/main/res/layout/singin_fragment.xml
> +        android:layout_width="150dp"
why not `wrap_content`?

2017-03-13 12:32 UTC, diegomedina248 commented on app/src/main/res/layout/singin_fragment.xml
> +        android:id="@+id/imageView"
Use snake case for view resources (aka image_view)
Applies everywhere (sorry)

2017-03-13 12:32 UTC, diegomedina248 commented on app/src/main/res/layout/singin_fragment.xml
> +            android:background="#ff3366"
move to colors and use the resource instead

2017-03-13 12:32 UTC, diegomedina248 commented on app/src/main/res/layout/singin_fragment.xml
> +            android:textColor="#ffffff"
here too

2017-03-13 12:32 UTC, diegomedina248 commented on app/src/main/res/layout/singin_fragment.xml
> +            android:clickable="true"
isn't this the default?

2017-03-13 12:32 UTC, diegomedina248 commented on app/src/main/res/layout/singin_fragment.xml
> +            android:textColor="#ffffff"
(and everywhere else)

2017-03-13 12:32 UTC, diegomedina248 commented on app/src/main/res/layout/singup_fragment.xml
> +<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
move to new line

2017-03-13 12:32 UTC, diegomedina248 commented on app/src/main/res/layout/singup_fragment.xml
> +
remove space

2017-03-13 12:32 UTC, diegomedina248 commented on app/src/main/res/layout/singup_fragment.xml
> +
here too

2017-03-13 12:34 UTC, bryant1410 commented on app/src/main/java/com/xmartlabs/doapp/MilisecondsLocalDateAdapter.java
> +public class MilisecondsLocalDateAdapter extends TypeConverter<Long, LocalDate> {
We had discussed this, but it depends on the backend datetime formatting.

2017-03-13 12:41 UTC, diegomedina248 commented on app/src/main/java/com/xmartlabs/doapp/MilisecondsLocalDateAdapter.java
> +public class MilisecondsLocalDateAdapter extends TypeConverter<Long, LocalDate> {
Why? Isn't it just for DBFlow?

2017-03-13 12:43 UTC, bryant1410 commented on app/src/main/java/com/xmartlabs/doapp/MilisecondsLocalDateAdapter.java
> +public class MilisecondsLocalDateAdapter extends TypeConverter<Long, LocalDate> {
Oh, you are right

2017-03-14 03:34 UTC, mirland requested changes
try to use styles in the layout in order to make the code more readable. However, good job :smile:

2017-03-14 03:34 UTC, mirland commented on app/src/main/java/com/xmartlabs/doapp/ui/SingupFragment.java
> +        Snackbar.make(getView(), R.string.failed_create_account, Snackbar.LENGTH_SHORT).show();
check that the view is alive

2017-03-14 03:34 UTC, mirland commented on app/src/main/java/com/xmartlabs/doapp/ui/SingupFragment.java
> +  private boolean aFieldIsNotCompleted() {
positive name

2017-03-14 03:34 UTC, matir91 commented on app/src/main/java/com/xmartlabs/doapp/ui/SinginFragment.java
> +    userController.getUser(userEmail).subscribe(new SingleSubscriber<User>() {
put the subscribe in a new line

2017-03-14 03:34 UTC, matir91 commented on app/src/main/java/com/xmartlabs/doapp/ui/SingupFragment.java
> +  private boolean aFieldIsNotCompleted() {
also put something like, `AndShowErrorIfNeeded`

2017-03-14 03:34 UTC, matir91 commented on app/src/main/java/com/xmartlabs/doapp/ui/SingupFragment.java
> +    String stringDate = month + "/" + day + "/" + date.getYear();
use a date format https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html

2017-03-14 03:34 UTC, matir91 commented on app/src/main/res/layout/singin_fragment.xml
> +            android:background="#ffffff"
use color a resource

2017-03-14 03:34 UTC, matir91 commented on app/src/main/res/layout/singup_fragment.xml
> +        android:textColorHint="#ffffff"
resource

2017-03-14 03:34 UTC, matir91 commented on app/src/main/res/layout/singup_fragment.xml
> +            android:background="#ff3366"
resource

2017-03-14 03:34 UTC, matir91 commented on app/src/main/res/layout/singup_fragment.xml
> +            android:background="#ffffff"
too

2017-03-14 03:34 UTC, matir91 commented on app/src/main/res/layout/singup_fragment.xml
> +            android:background="#ffffff"
too

2017-03-14 03:34 UTC, matir91 commented on app/src/main/res/layout/singin_fragment.xml
> +            android:layout_marginEnd="25dp"
use app styles

2017-03-14 03:34 UTC, matir91 commented on app/src/main/res/values/styles.xml
> +        <item name="android:editTextColor">#ffffff</item>
use resources

2017-03-14 11:35 UTC, bryant1410 approved these changes

2017-03-14 11:35 UTC, bryant1410 commented on app/src/main/res/layout/singin_fragment.xml
> +            android:background="#ffffff"
It's recommended to set a color palette

2017-03-14 17:04 UTC, mirland approved these changes

2017-03-14 17:04 UTC, matir91 commented on app/src/main/java/com/xmartlabs/doapp/ui/SinginFragment.java
> +      @Override
indentation

2017-03-14 17:04 UTC, matir91 commented on app/src/main/java/com/xmartlabs/doapp/ui/SingupFragment.java
> +      public void onSuccess(User value) {
indentation

2017-03-14 17:06 UTC, merged