Adds an on boarding
chacaa/DoApp pull request #3
Opened 2017-03-14 18:36 UTC by chacaa

This feature adds an on boarding for the app.

## Trelo Card:
* [Onboarding logic](https://trello.com/c/DsnNx69F)
* [Setup on boarding images](https://trello.com/c/PoBK5Xte)

## UI:
![UI](http://g.recordit.co/5eUqPOaHXW.gif)

2017-03-14 19:36 UTC, mirland requested changes

2017-03-14 19:36 UTC, matir91 commented on app/src/main/AndroidManifest.xml
> +        <meta-data
remove the key

2017-03-14 19:36 UTC, matir91 commented on app/src/main/java/com/xmartlabs/doapp/ui/OnBoardingActivity.java
> +    createOnboardingCards("", "Create groups for different purpouses", R.drawable.tutorial_1);
use string resources

2017-03-14 19:36 UTC, matir91 commented on app/src/main/java/com/xmartlabs/doapp/ui/OnBoardingActivity.java
> +    setFinishButtonTitle("Let's Do it!");
too

2017-03-14 19:36 UTC, matir91 commented on app/src/main/java/com/xmartlabs/doapp/ui/OnBoardingActivity.java
> +  private void createOnboardingCards(String title, String description, @DrawableRes int iconId) {
all titles are empty, so remove it

2017-03-14 19:36 UTC, matir91 commented on app/src/main/java/com/xmartlabs/doapp/ui/StartActivity.java
> +}
add end line

2017-03-14 19:36 UTC, matir91 commented on app/src/main/res/values/colors.xml
> +    <color name="dark">#1d1d26</color>
change the color name, `color_dark`

2017-03-14 19:36 UTC, matir91 commented on app/src/main/AndroidManifest.xml
> +            android:name="com.xmartlabs.doapp.ui.OnBoardingActivity"
shouldn't be single task?

2017-03-14 19:36 UTC, matir91 commented on app/src/main/java/com/xmartlabs/doapp/ui/OnBoardingActivity.java
> +public class OnBoardingActivity extends AhoyOnboarderActivity {
I don't like it, does not it support fragments?

2017-03-14 20:21 UTC, chacaa commented on app/src/main/java/com/xmartlabs/doapp/ui/OnBoardingActivity.java
> +public class OnBoardingActivity extends AhoyOnboarderActivity {
It doesn't :(

2017-03-14 20:39 UTC, mirland requested changes

2017-03-14 20:39 UTC, matir91 commented on app/src/main/AndroidManifest.xml
> +            android:launchMode="singleTask"
indent the file

2017-03-14 20:39 UTC, matir91 commented on app/src/main/res/values/colors.xml
> +    <color name="color_dark">#1d1d26</color>
haha my bad, the color name should be something like `black_dark` or `blue_dark`. I don't know what color is `#1d1d26`

2017-03-14 20:54 UTC, mirland approved these changes

2017-03-14 20:54 UTC, merged

2017-03-15 13:32 UTC, bryant1410 commented
Just a comment: it's hard for background pictures to have the right size, as devices have different screen sizes. One possibility is to use "nodpi" with just one image and centered, and you see whatever fits.